// Generated by CoffeeScript 1.7.1
var argv, branch, exec, gitBranchDiff, repository;

exec = require('child_process').exec;

gitBranchDiff = require('..');

argv = require('yargs').usage("Returns list of files that are changed locally from specified remote branch.\nUsage: $0 -b branch -r repository").demand('b').alias('b', 'branch').describe('b', 'Branch against which to diff all local branches').demand('r').alias('r', 'repository').describe('r', 'Target repository').argv;

branch = argv.branch, repository = argv.repository;

gitBranchDiff(branch, repository).then(function(data) {
  return process.stdout.write(JSON.stringify(data, null, 2));
});
